version: "2"
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      # - "postgresql_data:/bitnami/postgresql"
      - "./data:/bitnami/postgresql"

  keycloak:
    image: docker.io/bitnami/keycloak:18
    volumes:
      - ./test:/test
      - ./themes:/opt/bitnami/keycloak/themes
    depends_on:
      - postgresql
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_EXTRA_ARGS="--spi-theme-welcome-theme=mastermindzh.tech"
    ports:
      - "10000:8080"
volumes:
  postgresql_data:
    driver: local
